package com.mtt.cryptocurrency.presentation.ui.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF8E1900)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFCD2D06)
val onPrimaryContainerLight = Color(0xFFFFFFFF)
val secondaryLight = Color(0xFFA13F29)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFFF9279)
val onSecondaryContainerLight = Color(0xFF4E0900)
val tertiaryLight = Color(0xFF5E4300)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFF8B6500)
val onTertiaryContainerLight = Color(0xFFFFFFFF)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFFFF8F6)
val onBackgroundLight = Color(0xFF281814)
val surfaceLight = Color(0xFFFFF8F6)
val onSurfaceLight = Color(0xFF281814)
val surfaceVariantLight = Color(0xFFFFDAD2)
val onSurfaceVariantLight = Color(0xFF5C403A)
val outlineLight = Color(0xFF906F68)
val outlineVariantLight = Color(0xFFE5BEB5)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF3E2C28)
val inverseOnSurfaceLight = Color(0xFFFFEDE9)
val inversePrimaryLight = Color(0xFFFFB4A3)

val primaryDark = Color(0xFFFFB4A3)
val onPrimaryDark = Color(0xFF630F00)
val primaryContainerDark = Color(0xFFBF2600)
val onPrimaryContainerDark = Color(0xFFFFFFFF)
val secondaryDark = Color(0xFFFFB4A3)
val onSecondaryDark = Color(0xFF621101)
val secondaryContainerDark = Color(0xFF78210E)
val onSecondaryContainerDark = Color(0xFFFFC9BD)
val tertiaryDark = Color(0xFFF0BF5C)
val onTertiaryDark = Color(0xFF412D00)
val tertiaryContainerDark = Color(0xFF7F5C00)
val onTertiaryContainerDark = Color(0xFFFFFFFF)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF1E100C)
val onBackgroundDark = Color(0xFFFADCD5)
val surfaceDark = Color(0xFF1E100C)
val onSurfaceDark = Color(0xFFFADCD5)
val surfaceVariantDark = Color(0xFF5C403A)
val onSurfaceVariantDark = Color(0xFFE5BEB5)
val outlineDark = Color(0xFFAC8981)
val outlineVariantDark = Color(0xFF5C403A)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFFADCD5)
val inverseOnSurfaceDark = Color(0xFF3E2C28)
val inversePrimaryDark = Color(0xFFB72400)
val surfaceDimDark = Color(0xFF1E100C)
val surfaceBrightDark = Color(0xFF483530)
val surfaceContainerLowestDark = Color(0xFF190A07)
val surfaceContainerLowDark = Color(0xFF281814)
val surfaceContainerDark = Color(0xFF2C1C18)
val surfaceContainerHighDark = Color(0xFF372622)
val surfaceContainerHighestDark = Color(0xFF43302C)

val primaryDarkMediumContrast = Color(0xFFFFBAAB)
val onPrimaryDarkMediumContrast = Color(0xFF340400)
val primaryContainerDarkMediumContrast = Color(0xFFFF5631)
val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
val secondaryDarkMediumContrast = Color(0xFFFFBAAB)
val onSecondaryDarkMediumContrast = Color(0xFF340400)
val secondaryContainerDarkMediumContrast = Color(0xFFE26F55)
val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
val tertiaryDarkMediumContrast = Color(0xFFF5C360)
val onTertiaryDarkMediumContrast = Color(0xFF201400)
val tertiaryContainerDarkMediumContrast = Color(0xFFB58A2C)
val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
val errorDarkMediumContrast = Color(0xFFFFBAB1)
val onErrorDarkMediumContrast = Color(0xFF370001)
val errorContainerDarkMediumContrast = Color(0xFFFF5449)
val onErrorContainerDarkMediumContrast = Color(0xFF000000)
val backgroundDarkMediumContrast = Color(0xFF1E100C)
val onBackgroundDarkMediumContrast = Color(0xFFFADCD5)
val surfaceDarkMediumContrast = Color(0xFF1E100C)
val onSurfaceDarkMediumContrast = Color(0xFFFFF9F8)
val surfaceVariantDarkMediumContrast = Color(0xFF5C403A)
val onSurfaceVariantDarkMediumContrast = Color(0xFFE9C2B9)
val outlineDarkMediumContrast = Color(0xFFBF9B93)
val outlineVariantDarkMediumContrast = Color(0xFF9D7B74)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFFADCD5)
val inverseOnSurfaceDarkMediumContrast = Color(0xFF372622)
val inversePrimaryDarkMediumContrast = Color(0xFF8E1900)
val surfaceDimDarkMediumContrast = Color(0xFF1E100C)
val surfaceBrightDarkMediumContrast = Color(0xFF483530)
val surfaceContainerLowestDarkMediumContrast = Color(0xFF190A07)
val surfaceContainerLowDarkMediumContrast = Color(0xFF281814)
val surfaceContainerDarkMediumContrast = Color(0xFF2C1C18)
val surfaceContainerHighDarkMediumContrast = Color(0xFF372622)
val surfaceContainerHighestDarkMediumContrast = Color(0xFF43302C)

val primaryDarkHighContrast = Color(0xFFFFF9F8)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFFFFBAAB)
val onPrimaryContainerDarkHighContrast = Color(0xFF000000)
val secondaryDarkHighContrast = Color(0xFFFFF9F8)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFFFFBAAB)
val onSecondaryContainerDarkHighContrast = Color(0xFF000000)
val tertiaryDarkHighContrast = Color(0xFFFFFAF7)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFFF5C360)
val onTertiaryContainerDarkHighContrast = Color(0xFF000000)
val errorDarkHighContrast = Color(0xFFFFF9F9)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFBAB1)
val onErrorContainerDarkHighContrast = Color(0xFF000000)
val backgroundDarkHighContrast = Color(0xFF1E100C)
val onBackgroundDarkHighContrast = Color(0xFFFADCD5)
val surfaceDarkHighContrast = Color(0xFF1E100C)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF5C403A)
val onSurfaceVariantDarkHighContrast = Color(0xFFFFF9F8)
val outlineDarkHighContrast = Color(0xFFE9C2B9)
val outlineVariantDarkHighContrast = Color(0xFFE9C2B9)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFFADCD5)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF570C00)
val surfaceDimDarkHighContrast = Color(0xFF1E100C)
val surfaceBrightDarkHighContrast = Color(0xFF483530)
val surfaceContainerLowestDarkHighContrast = Color(0xFF190A07)
val surfaceContainerLowDarkHighContrast = Color(0xFF281814)
val surfaceContainerDarkHighContrast = Color(0xFF2C1C18)
val surfaceContainerHighDarkHighContrast = Color(0xFF372622)
val surfaceContainerHighestDarkHighContrast = Color(0xFF43302C)







